# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/ruby:3.2.1
        environment:
          PGHOST: localhost
          PGUSER: quoting
          RAILS_ENV: test

      - image: postgres:9.5.20-alpine
        environment:
          POSTGRES_USER: quoting
          POSTGRES_DB: quoting_circle_ci
          POSTGRES_PASSWORD: "password"

    working_directory: ~/Quoting
    environment:
      DEFAULT_URL: localhost:3000

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: cp config/database.yml.ci config/database.yml
      - run: bundle exec rake db:drop
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate
      # run tests!
      # Change to rspec if you are using rspec
      - run:
          name: run rspec
          command: bundle exec rspec

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
